config/routes.rb
TinyDevchart::Application.routes.draw do

  devise_for :users
  root :to => 'development_times#index'

  resources :development_times do
  	collection do
  		get 'search'
  	end
  end

  resources :films
  resources :developers
end

app/models/developer.rb
class Developer < ActiveRecord::Base
  validates :name, :brand, presence: true
  validates :name, uniqueness: true

  has_many :development_times
end

app/models/development_time.rb
class DevelopmentTime < ActiveRecord::Base
  belongs_to :film
  belongs_to :developer

  validates :seconds, :dillution, presence: true

  after_initialize :set_defaults

  def set_defaults
    self.rating ||= 3
    self.iso ||= 100
    self.temperature ||= 20
  end
end

app/models/film.rb
class Film < ActiveRecord::Base
  validates :name, :brand, :iso, presence: true
  validates :name, uniqueness: true

  has_many :development_times
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  def admin?
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
	before_filter :set_developer, only: [:show, :edit, :update]
	before_filter :authenticate_user!, only: [:index, :new, :create, :edit, :update]

	def index
		@developers = Developer.all
		authorize @developers
	end

	def new
		@developer = Developer.new
		authorize @developer
	end

	def create
		@developer = Developer.new(developer_params)
		authorize @developer

		if @developer.save
			redirect_to developer_path(@developer)
		else
			render action: :new
		end
	end

	def show
	end

	def edit
		authorize @developer
	end

	def update
		authorize @developer

		if @developer.save!
			redirect_to developer_path(@developer)
		else
			render action: :edit
		end
	end

	private
	def developer_params
		params.require(:developer).permit(:brand, :name)
	end

	def set_developer
		@developer = Developer.find( params[:id] )
	end
end

app/controllers/development_times_controller.rb
class DevelopmentTimesController < ApplicationController
	before_filter :authenticate_user!, only: [:new, :create, :edit, :update]

	def index
		@development_times = DevelopmentTime.all
	end

	def new
		@development_time = DevelopmentTime.new
	end

	def create
		@development_time = DevelopmentTime.new( development_time_params )
		if @development_time.save
			redirect_to development_times_path
		else
			render action: :edit
		end
	end

	def edit
		@development_time = DevelopmentTime.find( params[:id] )
	end

	private
	def development_time_params
		params.require(:development_time).permit(:developer_id, :dillution, :film_id, :iso, :notes, :rating, :seconds, :temperature)
	end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
	before_filter :set_film, only: [:show, :edit, :update]
	before_filter :authenticate_user!, only: [:index, :new, :create, :edit, :update]

	def index
		@films = Film.all
		authorize @films
	end

	def new
		@film = Film.new
		authorize @film
	end

	def create
		@film = Film.new( film_params )
		authorize @film

		if @film.save
			redirect_to film_path( @film )
		else
			render action: :new
		end
	end

	def show
	end

	def edit
		authorize @film
	end

	def update
		authorize @film

		if @film.save
			redirect_to film_path(@film)
		else
			render action: :edit
		end
	end

	private
	def film_params
		params.require(:film).permit(:brand, :iso, :name)
	end

	def set_film
		@film = Film.find( params[:id] )
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/development_time_helper.rb
module DevelopmentTimeHelper
  def humanize secs
    minutes, seconds = secs.divmod(60)
    "#{minutes}:#{seconds.to_s.rjust(2, '0')}"
  end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/developers/_developer.html.erb
<tr>
  <td>
    <%= developer.brand %>
  </td>
  <td>
    <%= link_to developer.name, developer_path( developer ) %>
  </td>
  <td>
    <%= developer.development_times.count %>
  </td>
  <td class="align_right">
    <%= link_to 'edit', edit_developer_path( developer ) %>
  </td>
</tr>

app/views/developers/_form.html.erb
<%= simple_form_for developer do |f| %>
  <%= f.input :name %>
  <%= f.input :brand %>

  <div class="clearfix">
    <%= f.submit class: "btn pull-right" %>
  </div>
  <% end %>

app/views/developers/edit.html.erb
<div class="base_form">
  <h2>edit developer</h2>

  <%= render partial: 'form', locals: { developer: @developer } %>
</div>

app/views/developers/index.html.erb
<hr>

<div class="table_wraper">
  <table class="dev_time_table">
    <thead>
      <tr>
        <th>brand</th>
        <th>name</th>
        <th>recipie count</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= render @developers %>
    </tbody>
  </table>
<div>

<hr>

<% if user_signed_in? %>
  <div class="clearfix">
    <%= link_to "add a new developer", :new_developer, class: "table_add_link btn" %>
  </div>
<% end %>

app/views/developers/new.html.erb
<div class="base_form">
  <h2>new developer</h2>

  <%= render partial: 'form', locals: { developer: @developer } %>
</div>

app/views/developers/show.html.erb
<h2><%= @developer.brand %> <%= @developer.name %></h2>

<%= render partial: 'development_times/table',
            locals: { development_times: @developer.development_times} %>

app/views/development_times/_development_time.html.erb
<tr>
	<td> <%= link_to development_time.film.name, film_path( development_time.film ) %> </td>
	<td class="align_right"> <%= development_time.iso %> </td>
	<td> <%= link_to development_time.developer.name, developer_path( development_time.developer )  %> </td>
	<td class="align_center"> <%= development_time.dillution %> </td>
	<td class="align_center"> <%= humanize development_time.seconds %> </td>
	<td class="align_center"> <%= development_time.temperature %>&deg;C </td>
	<td class="align_right"> <%= development_time.rating %> </td>
</tr>

app/views/development_times/_form.html.erb
<%= simple_form_for development_time do |f| %>
  <div>
    <div class="clearfix">
      <%= f.association :film, include_blank: false, input_html: { class: "film pull-right" }  %>
    </div>

    <div class="clearfix">
      <%= f.input :iso, placeholder: "100", input_html: { class: "iso pull-right" }  %>
    </div>
  </div>

  <div>
    <div class="clearfix">
      <%= f.association :developer, include_blank: false, input_html: { class: "developer pull-right" }  %>
    </div>

    <div class="clearfix">
      <%= f.input :dillution, placeholder: "1:63", input_html: { class: "dillution pull-right" }  %>
    </div>

    <div class="clearfix">
      <%= f.input :temperature,
                  placeholder: "20",
                  input_html: { class: "temperature pull-right" },
                  html: {class: "inline"} %>
    </div>
  </div>

  <div
  <div class="clearfix">
    <%= f.input :seconds, placeholder: "300", input_html: { class: "time pull-right" }  %>
  </div>

  <hr>

  <div class="clearfix">
    <%= f.input :rating, default: "3", input_html: { class: "rating, pull-right" } %>
  </div>

  <div class="clearfix">
    <%= f.input :notes, input_html: { class: "pull-right", rows: "5" }  %>
  </div>

  <hr>

  <div class="clearfix">
    <%= f.submit class: "btn pull-right" %>
  </div>
<% end %>

app/views/development_times/_table.html.erb
<hr>

<div class="table_wraper">
  <table class="dev_time_table">
    <%= render 'development_times/table_head' %>
    <tbody>
      <%= render development_times %>
    </tbody>
  </table>
<div>

<hr>

app/views/development_times/_table_head.html.erb
<thead>
  <tr>
    <th>film</th>
    <th class="align_right">ISO</th>
    <th>developer</th>
    <th class="align_center">dillution</th>
    <th class="align_center">time</th>
    <th class="align_center">temperature</th>
    <th class="align_right">rating</th>
  </tr>
</thead>

app/views/development_times/edit.html.erb
<div id="new_dev_time">
  <h2>new development time</h2>

  <%= render 'form', development_time: @development_time %>
</div>

app/views/development_times/index.html.erb
<div class="main">

  <% if user_signed_in? %>
    <div class="clearfix">
      <%= link_to "add a new time", :new_development_time, class: "table_add_link btn" %>
    </div>
  <% end %>


  <%= render partial: 'table', locals: { development_times: @development_times } %>
</div>

app/views/development_times/new.html.erb
<div id="new_dev_time">
  <h2>new development time</h2>

  <%= render 'form', development_time: @dev_time %>
</div>

app/views/development_times/search.html.erb
<h1>The <span class="focus">Tiny</span> Dev Chart</h1>
enter a film or developer:

<% form_tag development_times_path, :action => 'search' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "search", :name => nil %>
  </p>
<% end %>

app/views/films/_film.html.erb
<tr>
  <td>
    <%= film.brand %>
  </td>
  <td>
    <%= link_to film.name, film_path( film ) %>
  </td>
  <td>
    <%= film.development_times.count %>
  </td>
  <td class="align_right">
    <%= link_to 'edit', edit_film_path( film ) %>
  </td>
</tr>

app/views/films/_form.html.erb
<%= simple_form_for film do |f| %>
  <%= f.input :name, placeholder: "TX-400" %>
  <%= f.input :brand, placeholder: "Fuji" %>
  <%= f.input :iso, placeholder: "200" %>

  <div class="clearfix">
    <%= f.submit class: "btn pull-right" %>
  </div>
<% end %>

app/views/films/edit.html.erb
<div class="base_form">
  <h2>edit film</h2>

  <%= render partial: 'form', locals: { film: @film } %>
</div>

app/views/films/index.html.erb
<hr>

<div class="table_wraper">
  <table class="dev_time_table">
    <thead>
      <tr>
        <th>brand</th>
        <th>name</th>
        <th>ISO</th>
        <th>recipie count</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= render @films %>
    </tbody>
  </table>
<div>

<hr>

<% if user_signed_in? %>
  <div class="clearfix">
    <%= link_to "add a new film", :new_film, class: "table_add_link btn" %>
  </div>
<% end %>

app/views/films/new.html.erb
<div class="base_form">
  <h2>new film</h2>

  <%= render partial: 'form', locals: { film: @film } %>
</div>

app/views/films/show.html.erb
<h2><%= @film.brand %> <%= @film.name %></h2>
<p>Native ISO: <%= @film.iso %></p>

<%= render partial: 'development_times/table',
            locals: { development_times: @film.development_times} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Tiny Dev Chart</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport"
    content="user-scalable=no, width=device-width" />

  <link href='http://fonts.googleapis.com/css?family=Noto+Serif:400,400italic' rel='stylesheet' type='text/css'>
</head>
<body>
  <%= render partial: 'shared/navigation' %>
  <h1>The <span class="focus">Tiny</span> Dev Chart</h1>
  <div class='main'>
    <%= yield %>
  </div>
</body>
</html>

app/views/shared/_login_items.html.erb
<% if user_signed_in? %>
  <li class="login">
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
  </li>
<% else %>
  <li class="login">
    <%= link_to('Login', new_user_session_path)  %>
  </li>
<% end %>
<div class="clearfix"></div>

app/views/shared/_navigation.html.erb
<ul class="navigation">
  <%= render partial: 'shared/login_items' %>
</ul>